// frontend/src/Canvas.tsx
import { useEffect, useRef } from "react";

import { LogDebug } from '@wailsjs/runtime';

export interface CanvasProps {
  columns: number;
  rows: number;
  cells: boolean[][] | null;
};

export const Canvas = (props: CanvasProps) => {
  const {columns, rows, cells} = props;

  const canvasRef = useRef<HTMLCanvasElement | null>(null);
  const draw = (ctx: CanvasRenderingContext2D) => {
    ctx.clearRect(0, 0, ctx.canvas.width, ctx.canvas.height);

    if (cells === null) {
      return;
    }

    const cellSize = ctx.canvas.width/columns;

    for (let i = 0; i < rows; i++) {
      for (let j = 0; j < columns; j++) {
        ctx.strokeStyle = '#7f7f7f';
        ctx.fillStyle = '#ffff7f';

        const path = new Path2D();
        path.arc((j+0.5)*cellSize, (i+0.5)*cellSize, cellSize/2, 0, Math.PI*2)

        if (cells[i][j]) {
          ctx.fill(path);
        } else {
          ctx.stroke(path);
        }
      }
    }
  };

  useEffect(() => {
    if (canvasRef.current === null) {
      return;
    }

    const canvas: HTMLCanvasElement | null = canvasRef.current;
    const ctx = canvas.getContext("2d");
    if (ctx === null) {
      return;
    }
    
    draw(ctx);
  }, [canvasRef.current, draw]);

  return (
    <canvas width="600" height="600" ref={canvasRef} className="">
      Canvas not supported
    </canvas>
  )
};

// frontend/src/app/canvas/canvas.component.ts
import { Component, computed, effect, ElementRef, inject, viewChild } from '@angular/core';
import { BoardService } from '../board.service';

@Component({
  selector: 'app-canvas',
  imports: [],
  templateUrl: './canvas.component.html',
  styleUrl: './canvas.component.scss'
})
export class CanvasComponent {
  canvas = viewChild.required<ElementRef<HTMLCanvasElement>>('canvas');
  private boardService = inject(BoardService);
  generation = computed(() => this.boardService.board().generation);

  constructor() { 
    effect(() => {
      const ctx = this.canvas().nativeElement.getContext("2d");
      if (ctx === null) {
        return;
      }
      this.draw(ctx);
    });
  }

  draw(ctx: CanvasRenderingContext2D) {
    ctx.clearRect(0, 0, ctx.canvas.width, ctx.canvas.height);

    var style = window.getComputedStyle(document.body);

    if (this.boardService.board() === undefined) {
      return;
    }

    const cellSize = ctx.canvas.width / this.boardService.board().columns;

    for (let i = 0; i < this.boardService.board().rows; i++) {
      for (let j = 0; j < this.boardService.board().columns; j++) {
        ctx.strokeStyle = style.getPropertyValue('--mat-sys-secondary');
        ctx.fillStyle = '#ffff7f';

        const path = new Path2D();
        path.arc(
          (j + 0.5) * cellSize,
          (i + 0.5) * cellSize,
          cellSize / 2,
          0,
          Math.PI * 2
        );

        if (this.boardService.board().cells[i][j]) {
          ctx.fill(path);
        } else {
          ctx.stroke(path);
        }
      }
    }
  }
}

<div class="canvas">
    <p>Generation: {{generation()}}
    </p>
    <canvas width="600" height="600" #canvas></canvas>
</div>
