// frontend/src/app/toolbar/toolbar.component.ts
import { Component, computed, inject } from '@angular/core';

import { BoardService } from '../board.service';

@Component({
  selector: 'app-toolbar',
  imports: [
  ],
  templateUrl: './toolbar.component.html',
  styleUrl: './toolbar.component.scss'
})
export class ToolbarComponent {

  private boardService = inject(BoardService);

  startButtonText = computed(() => this.boardService.running() ? "Stop" : "Start");

  toggleStatus() {
    this.boardService.toggleStatus();
  }

  reset() {
    this.boardService.reset();
  }

  next() {
    this.boardService.next();
  }
}

<div class="toolbar">
    <button class="btn btn-primary" (click)="toggleStatus()">{{startButtonText()}}</button>
    <button class="btn btn-primary" (click)="next()">Next</button>
    <button class="btn btn-primary" (click)="reset()">Reset</button>
</div>

// frontend/src/Toolbar.tsx
export interface ToolbarProps {
  running: boolean,
  onStartStop: () => void;
  onReset: () => void;
  onNext: () => void;
}

export const Toolbar = (props: ToolbarProps) => {
  const startButtonText = (props.running) ? "Stop": "Start";

  return (
    <div className="flex flex-row gap-4">
      <button id="start-button" className="btn btn-primary" onClick={props.onStartStop}>
        {startButtonText}
      </button>
      <button className="btn btn-primary" disabled={props.running} onClick={props.onNext}>
        Next
      </button>
      <button className="btn btn-primary" disabled={props.running} onClick={props.onReset}>
        Reset
      </button>
    </div>
  );
}
